polls/urls.py
from django.urls import path,re_path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.home, name='home'),
    path('mypolls/', views.list_by_user, name='list_by_user'),
    path('create/', views.createpoll, name='createpoll'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('result/<int:poll_id>/', views.poll_result, name='result'),
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
    path('contact/', views.contact, name='contact'),
    # path('mypolls/<int:poll_id>/', views.poll_detail, name='detail'),
]

# urlpatterns = [
#     path('list/', views.polls_list, name='list'),
#     path('list/user/', views.list_by_user, name='list_by_user'),
#     path('add/', views.polls_add, name='add'),
# ]

votingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls')),
    # path('__debug__/',include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import secrets
# Create your models here.


class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    poll_text = models.TextField()
    poll_date = models.DateTimeField(default=timezone.now)
    poll_status = models.BooleanField(default=True)

    def user_can_vote(self, user):
        users_vote = user.vote_set.all()
        uv = users_vote.filter(poll=self)

        if uv.exists():
            return False
        return True

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def get_result_dict(self):
        res = []
        for choice in self.choice_set.all():
            dict = {}
            alert_class = ['primary', 'secondary', 'success',
                           'danger', 'dark', 'warning', 'info']
            dict['alert_class'] = secrets.choice(alert_class)
            dict['text'] = choice.choice_text
            dict['num_votes'] = choice.get_vote_count

            if not self.get_vote_count:
                dict['percentage'] = 0
            else:
                dict['percentage'] = (
                    choice.get_vote_count/self.get_vote_count)*100
            res.append(dict)
        return res

    def __str__(self):
        return f"{self.poll_text}"


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def __str__(self):
        return f"{self.poll.poll_text[:25]}-{self.choice_text[:25]}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.poll.poll_text[:25]}-{self.choice.choice_text[:25]}-{self.user.username}"


class Result(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    result = models.ImageField(upload_to="images/", default=None)

    def __str__(self):
        return f"{self.poll.poll_text[:25]}-RESULT"


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self) -> str:
        return f"{self.name}-{self.email}-{self.subject}"

polls/forms.py
from django import forms
from .models import Poll, Choice,Contact


class EditPollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['poll_text',]
        widgets = {
            'poll_text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'columns': 20, }),
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text',]
        widgets = {
            'choice_text': forms.TextInput(attrs={'class': 'form-control', }),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

    # Add Bootstrap classes to form widgets
    widgets = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.EmailInput(attrs={'class': 'form-control'}),
        'subject': forms.TextInput(attrs={'class': 'form-control'}),
        'message': forms.Textarea(attrs={'class': 'form-control'}),
    }

polls/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,EmptyPage
from django.contrib import messages
from polls.forms import EditPollForm, ChoiceForm, ContactForm
from .models import Poll, Choice, Vote, Contact
from django.contrib.auth.models import User
from django.db.models import Count
# Create your views here.


@login_required
def home(request):
    all_polls = Poll.objects.all()
    # print(all_polls)
    search_term = ''
    try:
        if 'name' in request.GET:
            all_polls = all_polls.order_by('poll_text')

        if 'date' in request.GET:
            all_polls = all_polls.order_by('poll_date')

        if 'vote' in request.GET:
            all_polls = all_polls.annotate(
                Count('vote')).order_by('vote__count')

        if 'search' in request.GET:
            search_term = request.GET['search']
            all_polls = all_polls.filter(text__icontains=search_term)
    except:
        pass
    paginator = Paginator(all_polls, 6)
    # print(paginator.count)
    page = request.GET.get('page')
    # print(page)
    polls = paginator.get_page(page)
    # print(polls)

    dict_copy = request.GET.copy()
    params = dict_copy.pop('page', True) and dict_copy.urlencode()
    context = {
        'polls': polls,
        'params': params,
        'search_term': search_term,
    }
    # print(polls)
    # print(params)
    return render(request, 'polls/index.html', context)


@login_required()
def createpoll(request):
    if request.method == "POST":
        try:
            flag = False
            msg = ""
            poll_text = request.POST['poll-text']
            if not poll_text:
                flag = True
                msg += "Please check your poll."
            num_choices = int(request.POST['choices'])
            if num_choices < 2 or num_choices > 10:
                msg += "Please enter number of choice in range(2-10)."
                flag = True
            for i in range(num_choices):
                choice_text = request.POST['choice'+str(i+1)]
                if not choice_text:
                    msg += "Please enter choice."
                    flag = True
                    break
            if flag:
                messages.error(
                    request, msg, extra_tags='alert alert-warning alert-dismissible fade show')
                return render(request, 'polls/create.html')
            # Get User
            owner = User(request.user)
            # print(owner)

            # save poll
            poll = Poll(owner=owner.id, poll_text=poll_text)
            poll.save()
            poll_id = Poll(poll).id

            # save choices
            for i in range(num_choices):
                choice_text = request.POST['choice'+str(i+1)]
                choice = Choice(poll=poll_id, choice_text=choice_text)
                choice.save()

            # user = User(id=request.user.id)
            # print(user)
            messages.success(
                request, "Poll created successfully", extra_tags='alert alert-success alert-dismissible fade show')
            return render(request, 'polls/create.html')
        # except MultiValueDictKeyError:
        except:
            return render(request, 'polls/create.html')
    return render(request, 'polls/create.html')

@login_required()
def list_by_user(request):
    all_polls = Poll.objects.filter(owner=request.user)
    paginator = Paginator(all_polls, 6)
    # print("Start")
    # print(paginator.count)
    # print("End")

    page = request.GET.get('page')
    polls = paginator.get_page(page)
    # print("Start")
    # print(polls.count)
    # print("End")

    context = {
        'polls': polls,
    }
    return render(request, 'polls/index.html', context)

@login_required
def poll_result(request, poll_id):
    poll = get_object_or_404(Poll, id=int(poll_id))

    # Check if the user is the owner of the poll
    if request.user == poll.owner:
        context = {'poll': poll}
        return render(request, 'polls/result.html', context)
    else:
        messages.error(request, "You do not have permission to view this poll's results.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("polls:home")

@login_required
def poll_detail(request, poll_id):
    poll = get_object_or_404(Poll, id=int(poll_id))

    if not poll.poll_status:
        return redirect("polls:result", poll_id=poll_id)

    context = {'poll': poll}
    return render(request, 'polls/detail.html', context)


@login_required
def polls_edit(request, poll_id):
    try:
        poll = get_object_or_404(Poll, pk=poll_id)
    except Poll.DoesNotExist:
        messages.error(request, "Sorry, poll doesn't exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('polls:list_by_user')

    if request.user != poll.owner:
        messages.error(request, "Sorry, you can't edit other people's polls.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('polls:home')
    
    if not poll.poll_status:
        messages.error(request, "Sorry, you can't edit ended polls", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('polls:list_by_user')

    if request.method == 'POST':
        form = EditPollForm(request.POST, instance=poll)
        if form.is_valid():
            form.save()
            messages.success(request, "Poll updated successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            return redirect("polls:list_by_user")

    else:
        form = EditPollForm(instance=poll)

    return render(request, "polls/edit.html", {'form': form, 'poll': poll})



@login_required
def polls_delete(request, poll_id):
    try:
        poll = get_object_or_404(Poll, pk=poll_id)
    except Poll.DoesNotExist:
        messages.error(request, "Poll does not exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("home")

    if request.user != poll.owner:
        messages.error(request, "You can't delete other people's polls.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('home')

    poll.delete()
    messages.success(request, "Poll deleted successfully.", extra_tags='alert alert-success alert-dismissible fade show')
    return redirect("polls:list_by_user")



@login_required
def add_choice(request, poll_id):
    try:
        poll = get_object_or_404(Poll, pk=poll_id)
    except Poll.DoesNotExist:
        messages.error(request, "Poll does not exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("home")

    if request.user != poll.owner:
        messages.error(request, "You can't add choices to other people's polls.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('polls:home')

    if request.method == 'POST':
        form = ChoiceForm(request.POST)
        if form.is_valid():
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(request, "Choice added successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:edit', poll.id)
    else:
        form = ChoiceForm()

    context = {
        'form': form,
    }
    return render(request, 'polls/add_choice.html', context)




@login_required
def choice_edit(request, choice_id):
    try:
        choice = get_object_or_404(Choice, pk=choice_id)
        poll = get_object_or_404(Poll, pk=choice.poll.id)
    except Choice.DoesNotExist:
        messages.error(request, "Choice does not exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("home")
    except Poll.DoesNotExist:
        messages.error(request, "Poll does not exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("home")

    if request.user != poll.owner:
        messages.error(request, "You can't edit choices for other people's polls.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('home')

    if request.method == 'POST':
        form = ChoiceForm(request.POST, instance=choice)
        if form.is_valid():
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(request, "Choice updated successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:edit', poll.id)
    else:
        form = ChoiceForm(instance=choice)

    context = {
        'form': form,
        'edit_choice': True,
        'choice': choice,
    }
    return render(request, 'polls/add_choice.html', context)




@login_required
def choice_delete(request, choice_id):
    try:
        choice = get_object_or_404(Choice, pk=choice_id)
        poll = get_object_or_404(Poll, pk=choice.poll.id)
    except Choice.DoesNotExist:
        messages.error(request, "Choice does not exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("home")
    except Poll.DoesNotExist:
        messages.error(request, "Poll does not exist.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect("home")
    
    if request.user != poll.owner:
        messages.error(request, "You can't delete choices for other people's polls.", extra_tags="alert alert-danger alert-dismissible fade show")
        return redirect('home')

    choice.delete()
    messages.success(request, "Choice deleted successfully.", extra_tags='alert alert-success alert-dismissible fade show')
    return redirect('polls:edit', poll.id)



@login_required
def poll_vote(request, poll_id):
    try:
        poll = get_object_or_404(Poll, pk=poll_id)

templates/polls/add_choice.html
{% extends 'base.html' %}


{% block title %}
    Add choice into your poll
{% endblock title %}
    

{% block content %}
<div class="container my-5 py-5 pb-5" style="min-height: 25rem;">
    <div class="row my-5 py-5 pb-5 d-flex justify-content-center align-items-center">
        <div class="col-md-6 shadow p-4">
            <div class="col-md-12">
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {% if edit_choice %}
            <h2 class="text-center">Update Choice</h2>
            {% else %}
            <h2 class="text-center">Add New Choice</h2>
            {% endif %}

            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="mb-3">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div class="text-center">
                    {% if edit_choice %}
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a class="btn btn-danger" href="{% url 'polls:choice_delete' choice.id %}" role="button"
                        onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                    {% else %}
                    <button type="submit" class="btn btn-primary">Add</button>
                    {% endif %}
                    <a href="{% url 'polls:home' %}" class="btn btn-warning text-light"><i class="fas fa-backward"></i>
                        Poll</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/polls/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Create new poll
{% endblock title %}

{% block content %}
<div class="container my-5 py-5 pb-5" style="min-height: 25rem;">
    <div class="row my-2 justify-content-center">
        <div class="col-md-8">
            <div class="col-md-12">
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center">Create Your Poll</h2>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="pollText" class="form-label">Poll</label>
                            <textarea class="form-control" id="pollText" name="poll-text" rows="3" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="choices" class="form-label">Number of Choices</label>
                            <div class="input-group">
                                <input class="form-control" type="number" id="choices" name="choices" min="2" max="10"
                                    value="2" required>
                                <button class="btn btn-success" type="button" onclick="createChoices()"><i
                                        class="fas fa-check text-light"></i></button>
                            </div>
                        </div>
                        <div class="mb-3" id="input-container">
                            <!-- This is where choices will be added dynamically -->
                        </div>
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary"><i class="fas fa-check text-light"></i>
                                Create</button>
                            <a href="../create/" class="btn btn-danger text-light"><i class="fas fa-times"></i>
                                Cancel</a>
                            <a href="../" class="btn btn-warning text-light"><i class="fas fa-backward"></i> Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'polls/create.js' %}"></script>
{% endblock js %}

templates/polls/detail.html
{% extends 'base.html' %}


{% block title %}
    Poll details - {{poll}}
{% endblock title %}
    

{% block content %}
<div class="container my-5 py-5 pb-5 d-flex justify-content-center align-items-center" style="min-height: 25rem;">
    <div class="col-md-10 offset-md-1 shadow p-5 my-5">
        {% if messages %}
        <div class="alert alert-dismissible">
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <h1 class="text-center">Polls Details</h1>
        <hr>
        <h2 class="mt-3 mb-3">{{ poll }}</h2>
        <form action="{% url 'polls:vote' poll.id %}" method="POST">
            {% csrf_token %}
            {% for choice in poll.choice_set.all %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}"
                    value="{{ choice.id }}">
                <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mt-3">Vote</button>
            <a class="btn btn-warning mt-3" href="{% url 'polls:home' %}" role="button">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/polls/edit.html
{% extends 'base.html' %}


{% block title %}
Edit your poll
{% endblock title %}


{% block content %}
<div class="container my-5 py-5 pb-5" style="min-height: 25rem;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="col-md-12">
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center">Edit Poll</h2>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="mb-3">
                            {{ field.errors }}
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <div class="d-flex justify-content-between flex-wrap">
                            <button type="submit" class="btn btn-primary m-1"><i class="fas fa-check text-light"></i>
                                Update</button>
                            <a class="btn btn-danger m-1" href="{% url 'polls:delete_poll' poll.id %}" role="button"
                                onclick="return confirm('Are you sure?')"><i class="fas fa-trash-alt"></i> Delete</a>
                            <a class="btn btn-warning m-1" href="{% url 'polls:add_choice' poll.id %}" role="button"><i
                                    class="fas fa-plus"></i> Add Choice</a>
                            <a href="{% url 'polls:home' %}" class="btn btn-warning m-1" role="button"><i
                                    class="fas fa-backward"></i> Back</a>
                        </div>
                    </form>

                    <div class="choices mt-4">
                        <h2 class="text-center">Choices</h2>
                        <hr>
                        <ul class="list-group">
                            {% for choice in poll.choice_set.all %}
                            <li class="list-group-item">
                                <a href="{% url 'polls:choice_edit' choice.id %}"
                                    class="btn btn-outline-primary btn-sm float-end"><i
                                        class="fas fa-pencil-alt"></i></a>
                                {{ choice.choice_text }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/polls/end.html
{% extends 'base.html' %}


{% block title %}
    Poll ended
{% endblock title %}
    

{% block content %}
<div class="container my-5 py-5 pb-5 d-flex justify-content-center align-items-center" style="min-height: 25rem;">
    <div class="col-md-10">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-md-6">
            <h3 class="mt-3 mb-3 text-center">Result for poll : {{ poll.text }}</h3>
            <!-- progress bar -->
            <div class="progress mt-3">

                {% for choice in poll.get_result_dict %}
                <div class="progress-bar bg-{{ choice.alert_class }}" role="progressbar"
                    style="width: {{ choice.percentage }}%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">
                    <b>{{ choice.text }}-{{ choice.percentage|floatformat }}%</b></div>
                {% endfor %}

            </div>
            <ul class="list-group">
                {% for choice in poll.choice_set.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.choice_text }}
                    <span class="badge badge-primary badge-pill">{{ choice.get_vote_count }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">Back To Polls</a>
        </div>

    </div>
</div>
{% endblock content %}

templates/polls/index.html
{% extends "base.html" %}


{% block title %}
    Welcome to VotingApp
{% endblock title %}


{% block content %}
<!-- Message Start-->
<div class="col-md-10 d-flex justify-content-center offset-md-1 my-5">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<!-- Message End-->
<div class="container my-5 pb-5" style="min-height: 25rem;">
    <div class="row my-5 d-flex justify-content-center align-items-center shadow rounded">
        <div class="col-md-6 py-2 pb-2">
            <h3 class="text-center m-3">Welcome to Poll List !</h3>


            <!-- Nav for home page -->
            <div class="mx-2">
                <a class="btn btn-{% if 'name' in request.GET %}warning{% else %}primary{% endif %} mb-3"
                    href="?name=True" role="button"><i class="fas fa-sort-alpha-down"></i>
                    Name</a>
                <a class="btn btn-{% if 'date' in request.GET %}warning{% else %}primary{% endif %} mb-3"
                    href="?date=True" role="button"><i class="far fa-clock"></i> Date</a>
                <a class="btn btn-{% if 'vote' in request.GET %}warning{% else %}primary{% endif %} mb-3"
                    href="?vote=True" role="button"><i class="fas fa-poll"></i> Vote</a>
                <a class="btn btn-success mb-3 float-end" href="{% url 'polls:createpoll' %}" role="button">Create <i
                        class="fas fa-plus"></i></a>
            </div>
            <!-- Nav for home page -->

            <!-- search area start -->
            <form class="form-inline d-flex flex-warp mb-4">
                <div class="form-group mx-2">
                    <input type="search" class="form-control" name="search" placeholder="Search"
                        value={{ search_term }}>
                </div>
                <button type="submit" class="btn btn-primary mx-2"><i class="fas fa-search"></i></button>
            </form>
            <!-- search area end -->

            <!-- Poll list  -->
            <ul class="list-group" style="height: 25rem;">

                {% if not polls %}
                <div class="my-5 p-5">
                    <h1 class="text-center my-4">No records found</h1>
                </div>
                {% else %}

                {% for poll in polls %}
                <li class="list-group-item mb-1 p-3">
                    <a class="text-decoration-none" href="{% url 'polls:detail' poll.id %}">{{ poll.poll_text }}
                        {% if not poll.poll_status%}
                        <i class="fas fa-check-circle ms-3"></i>
                        {% endif %}
                    </a>
                    {% if request.user == poll.owner %}
                    <a class="text-decoration-none float-end" href="{% url 'polls:result' poll.id %}">
                        <i class="fas fa-vote-yea float-end btn btn-success btn-sm me-3"></i>
                    </a>
                    {% if poll.poll_status %}
                    <a href="{% url 'polls:end_poll' poll.id %}" data-toggle="tooltip" data-placement="top"
                        title="End Poll" onclick="return confirm('Are you sure ?')"><i
                            class="fas fa-step-forward float-end btn btn-danger btn-sm me-3"></i></a>
                    <a href="{% url 'polls:edit' poll.id %}" data-toggle="tooltip" data-placement="top"
                        title="Edit Poll"><i class="fas fa-pencil float-end btn btn-primary btn-sm me-3"></i></a>
                    {% endif %}
                    {% endif %}
                </li>

                {% endfor %}
                {% endif %}
            </ul>
            <!-- poll listing end -->
            <nav class="mt-3">
                <ul class="pagination">
                    {% if polls.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1&{{ params }}">First</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ polls.previous_page_number }}&{{ params }}">Previous</a></li>
                    {% endif %}

                    <li class="page-item active"><a class="page-link" href="">{{ polls.number }}</a></li>

                    {% if polls.has_next %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ polls.next_page_number }}&{{ params }}">Next</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ polls.paginator.num_pages }}&{{ params }}">Last</a></li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    </div>
</div>
{% endblock content %}