accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
    path('send/', views.send_verification_code, name='send_verification_code'),
    path('verify/', views.verify_email, name='verify_email'),
]

polls/urls.py
from django.urls import path,re_path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.home, name='home'),
    path('mypolls/', views.list_by_user, name='list_by_user'),
    path('create/', views.createpoll, name='createpoll'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('result/<int:poll_id>/', views.poll_result, name='result'),
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
    path('contact/', views.contact, name='contact'),
    # path('mypolls/<int:poll_id>/', views.poll_detail, name='detail'),
]

# urlpatterns = [
#     path('list/', views.polls_list, name='list'),
#     path('list/user/', views.list_by_user, name='list_by_user'),
#     path('add/', views.polls_add, name='add'),
# ]

votingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls')),
    # path('__debug__/',include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<footer class="footer text-light bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="my-3 py-2 pb-4">
          <h3 class="text-center mb-4">Connect with us</h3>
          <div class="d-flex justify-content-around">
            <a href="https://www.linkedin.com/in/moti9/" target="_blank" class="btn btn-primary btn-social">
              <i class="fab fa-linkedin-in"></i>
            </a>
            <a href="https://github.com/moti9" target="_blank" class="btn btn-primary btn-social">
              <i class="fab fa-github"></i>
            </a>
            <a href="https://twitter.com/moti_kumar_" target="_blank" class="btn btn-primary btn-social">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="https://www.instagram.com/moti9_m/" target="_blank" class="btn btn-primary btn-social">
              <i class="fab fa-instagram"></i>
            </a>
          </div>
        </div>
        <div class="my-3 py-2 pb-2">
          <h3 class="text-center mb-4">Useful Links</h3>
          <ul class="list-unstyled d-flex justify-content-center p-2">
            <li class="mx-2 fw-bold"><a href="/home">Home</a></li>
            <li class="mx-2 fw-bold"><a href="/about">About</a></li>
            <li class="mx-2 fw-bold"><a href="/services">Services</a></li>
            <li class="mx-2 fw-bold"><a href="/blog">Blog</a></li>
            <li class="mx-2 fw-bold"><a href="/contact">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-6">
        <div class="my-3 py-2 pb-2">
          <h3 class="text-center">Contact Information</h3>
          <p>If you have any questions or need assistance, feel free to reach out to our support team.</p>
          <ul class="list-unstyled contact-info">
            <li class="my-2"><i class="fas fa-envelope"></i> Email: <a
                href="mailto:info@yourdomain.com">help@votingapp.com</a></li>
            <li class="my-2"><i class="fas fa-phone"></i> Phone: +11 987-326-4249</li>
            <li class="my-2"><i class="fas fa-map-marker-alt"></i> Address: 123 Main Street, Bhagalpur, Bihar, India</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/partials/navbar.html
{% load static %}
<style>
    /* Custom CSS for hover effect */
    .nav-item:hover .nav-link {
        color: #007BFF; /* Change the text color on hover */
    }
    .navbar-nav .nav-link:hover {
        color: #007BFF; /* Change the text color on hover */
    }
</style>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark d-flex justify-content-center flex-column sticky-top p-4 fw-bold">
    <div>
        <img style="width: 5rem;" src="{% static 'images/header.png' %}" alt="Vote image">
    </div>
    <div class="container text-bg-dark">
        <a class="navbar-brand mx-2" href="{% url 'home' %}"><i class="fas fa-poll"></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link active bold" href="{% url 'home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active bold" href="/polls">Polls</a>
                </li>
                {% endif %}
            </ul>
            <div class="navbar-nav ms-auto">
                {% if request.user.is_authenticated %}
                <a class="nav-link active bold" href="{% url 'polls:list_by_user' %}">My Polls</a>
                <a class="nav-link active bold" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                <a class="nav-link active bold" href="{% url 'accounts:login' %}">Login</a>
                <a class="nav-link active bold" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>