polls/urls.py
from django.urls import path,re_path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.home, name='home'),
    path('mypolls/', views.list_by_user, name='list_by_user'),
    path('create/', views.createpoll, name='createpoll'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('result/<int:poll_id>/', views.poll_result, name='result'),
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
    path('contact/', views.contact, name='contact'),
    # path('mypolls/<int:poll_id>/', views.poll_detail, name='detail'),
]

# urlpatterns = [
#     path('list/', views.polls_list, name='list'),
#     path('list/user/', views.list_by_user, name='list_by_user'),
#     path('add/', views.polls_add, name='add'),
# ]

votingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls')),
    # path('__debug__/',include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
{% load static  %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{% static 'images/header.png' %}" type="image/x-icon">
  <title>VotingApp | {% block title %}

    {% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
    .wrapper {
      min-height: 50vh;
    }

    .footer-div {
      bottom: 0;
      width: 100%;
      height: auto;
    }
  </style>
  {% block css %}

  {% endblock css %}
</head>

<body>
  {% include 'partials/navbar.html' %}
  <div class="wrapper">
    {% block content %}

    {% endblock content %}
  </div>
  <div class="footer-div">
    {% include 'partials/footer.html' %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
  {% block js %}

  {% endblock js %}
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
  Welcome to VotingApp
{% endblock title %}

{% block content %}
<div class="col-md-10 d-flex justify-content-center my-5 offset-md-1">
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
<div class="container shadow p-4 mb-4 my-5 rounded-1">

  <div class="my-2">
    <div class="jumbotron">
      <div class="container d-flex flex-wrap justify-content-center align-items-center flex-column">
        <h1>Welcome to Voting App!</h1>
        <p class="lead">Cast your vote and make your voice heard!</p>
        <a class="btn btn-primary btn-lg" href="polls" role="button">Explore Polling</a>
      </div>
    </div>
  </div>

  <!-- About Section -->
  <div id="about">
    <div class="container my-4">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2>About Voting App</h2>
          {% comment %}
          <hr> {% endcomment %}
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <p>Voting App is a web-based application that allows registered voters to cast their votes online. It provides
            a convenient and secure way for voters to participate in elections without having to physically go to a
            polling station.</p>
        </div>
        <div class="col-lg-6">
          <p>Voting App uses advanced encryption and authentication techniques to ensure the security and integrity of
            the voting process. It also provides real-time monitoring and auditing of the voting results to prevent
            fraud and manipulation.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Contact Section -->
<section id="contact" class="mb-4 ">
  <div class="container d-flex flex-wrap justify-content-center flex-column">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Contact Us</h2>
        {% comment %}
        <hr class="divider"> {% endcomment %}
      </div>
    </div>
    <div class="row p-4">
      <div class="col-lg-8 mx-auto p-4 shadow rounded">
        <form id="contact-form" method="POST" role="form" action="{% url 'polls:contact' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required>
          </div>
          <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Your Email" required>
          </div>
          <div class="form-group">
            <label for="subject">Subject</label>
            <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required>
          </div>
          <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" rows="5" id="message" name="message" placeholder="Your Message"
              required></textarea>
          </div>
          <div class="d-flex justify-content-center my-2">
            <button type="submit" class="btn btn-primary btn-block m-2">Send Message</button>
            <button type="reset" class="btn btn-danger btn-block m-2">Clear</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}